SaveTime.Web.Admin/Models/Company/CompanyDetailsViewModel.cs
using SaveTime.Web.Admin.Models.Branch;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Script.Serialization;

namespace SaveTime.Web.Admin.Models.Company
{
    public class CompanyDetailsViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        [ScriptIgnore]
        public List<BranchDetailsViewModel> Branches { get; set; }

    }
}

SaveTime.Web.Admin/Models/Company/CompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SaveTime.Web.Admin.Models.Company
{
    public class CompanyViewModel
    {
        //for Company/Index
        public IList<CompanyDetailsViewModel> Companies { get; set; } = new List<CompanyDetailsViewModel>();

        //for Company/Create
        public CreateCompanyViewModel CreateCompany { get; set; } = new CreateCompanyViewModel();
    }
}

SaveTime.Web.Admin/Models/Company/CreateCompanyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SaveTime.Web.Admin.Models.Company
{
    public class CreateCompanyViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
    }
}

SaveTime.Web.Admin/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using AutoMapper;
using Ninject;
using SaveTime.DataAccess;
using SaveTime.DataModel.Organization;
using SaveTime.Web.Admin.Models.Branch;
using SaveTime.Web.Admin.Models.Company;
using SaveTime.Web.Admin.Models.Employee;
using SaveTime.Web.Admin.Repo;

namespace SaveTime.Web.Admin.Controllers
{
    public class CompanyController : BaseController
    {
        readonly IRepository<Company> _repository;
        IMapper _mapper;

        public CompanyController()
        {
            _repository = kernel.Get<IRepository<Company>>();
            var config = new MapperConfiguration(
                c => 
                {
                    c.CreateMap<Employee, EmployeeDetailsViewModel>();
                    c.CreateMap<Branch, BranchDetailsViewModel>();
                    c.CreateMap<Company, CompanyDetailsViewModel>();
                }
                );
            _mapper = config.CreateMapper();
        }
        // GET: Company
        public ActionResult Index()
        {
            IEnumerable<Company> companies = _repository.GetAll();
            var company = new CompanyViewModel();

            foreach (var com in companies)
            {
                var cvm = _mapper.Map<CompanyDetailsViewModel>(com);
                company.Companies.Add(cvm);
            }

            return View(company);
        }

        // GET: Company/Details/5
        public ActionResult Details(int id)
        {

            Company company = _repository.GetById(id);
            if (company == null) return HttpNotFound();

            var companyDetails = _mapper.Map<CompanyDetailsViewModel>(company);

            //var companyDetails = new CompanyDetailsViewModel()
            //{
            //    Id = company.Id,
            //    Name = company.Name,
            //    City = company.City
            //};

            var branchDetails = new List<BranchDetailsViewModel>();

            foreach (var branch in company.Branches)
            {
                var branchDetail = _mapper.Map<BranchDetailsViewModel>(branch);
                //var branchDetail = new BranchDetailsViewModel
                //{
                //    Id = branch.Id,
                //    Address = branch.Address,
                //    Email = branch.Email,
                //    Phone = branch.Phone,
                //    StartWork = branch.StartWork,
                //    EndWork = branch.EndWork,
                //    StepWork = branch.StepWork
                //};

                IList<EmployeeDetailsViewModel> employeeDetails = new List<EmployeeDetailsViewModel>();
                foreach (var employee in branch.Employees)
                {

                    var employeeDetail = _mapper.Map<EmployeeDetailsViewModel>(employee);
                    //EmployeeDetailsViewModel employeeDetail = new EmployeeDetailsViewModel
                    //{
                    //    Id = employee.Id,
                    //    Name = employee.Name
                    //};
                    employeeDetails.Add(employeeDetail);
                }
                branchDetail.Employees = employeeDetails;
                branchDetails.Add(branchDetail);

            }
            companyDetails.Branches = branchDetails;

            return View(companyDetails);
        }

        // GET: Company/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Company/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public JsonResult Create(CreateCompanyViewModel createCompanyViewModel)
        {
            if (ModelState.IsValid && createCompanyViewModel!=null)
            {
                var c = new Company()
                {
                    Name = createCompanyViewModel.Name,
                    City = createCompanyViewModel.City
                };
                _repository.Create(c);
                return Json(c, JsonRequestBehavior.AllowGet);
            }

            return Json(createCompanyViewModel, JsonRequestBehavior.AllowGet);
        }

        // GET: Company/Edit/5
        public ActionResult Edit()
        {   
            return View();
        }

        // POST: Company/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в статье https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Edit(CreateCompanyViewModel createCompanyViewModel) 
        {
            if (ModelState.IsValid && createCompanyViewModel != null)
            {
                var company = _repository.GetById(createCompanyViewModel.Id);

               company.Id = createCompanyViewModel.Id;
                company.Name = createCompanyViewModel.Name;
                company.City = createCompanyViewModel.City;

                _repository.Edit(company);
                return Json(company, JsonRequestBehavior.AllowGet);
            }
                return Json(createCompanyViewModel, JsonRequestBehavior.AllowGet);
        }


        public JsonResult GetCompanies()
        {
            IEnumerable<Company> companies = _repository.GetAll();
            var companyVM = new List<CompanyDetailsViewModel>();

            foreach (var com in companies)
            {
                var cvm = _mapper.Map<CompanyDetailsViewModel>(com);
                companyVM.Add(cvm);
            }
            return Json(companyVM, JsonRequestBehavior.AllowGet);
        }

        //// GET: Company/Edit/5
        //public ActionResult Edit(int?id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }

        //    if (company == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(company);
        //}

    
        //// GET: Company/Delete/5
        //public ActionResult Delete(int? id)
        //{
        //    if (id == null)
        //    {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Company company = db.Companies.Find(id);
        //    if (company == null)
        //    {
        //        return HttpNotFound();
        //    }
        //    return View(company);
        //}

        //// POST: Company/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id)
        //{
        //    Company company = db.Companies.Find(id);
        //    db.Companies.Remove(company);
        //    db.SaveChanges();
        //    return RedirectToAction("Index");
        //}

        //protected override void Dispose(bool disposing)
        //{
        //    if (disposing)
        //    {
        //        db.Dispose();
        //    }
        //    base.Dispose(disposing);
        //}
    }
}

SaveTime.Web.Admin/Views/Company/Create.cshtml
@model SaveTime.Web.Admin.Models.Company.CreateCompanyViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SaveTime.Web.Admin/Views/Company/Delete.cshtml
@model SaveTime.DataModel.Organization.Company

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SaveTime.Web.Admin/Views/Company/Details.cshtml
@model SaveTime.Web.Admin.Models.Company.CompanyDetailsViewModel

@{
    ViewBag.Title = "Details";
    Layout = null;
}

<h2>Details</h2>

<div>
    <h4>Company</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.City)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.City)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
</p>

<h3>Branches for @Model.Name</h3>
<table class="table">
    @foreach (var branch in Model.Branches)
    {
        <tr>
            <td> @Html.DisplayFor(modelItem => branch.Phone) </td>
            <td> @Html.DisplayFor(modelItem => branch.Address) </td>
            <td> @Html.DisplayFor(modelItem => branch.StartWork) </td>
            <td> @Html.DisplayFor(modelItem => branch.EndWork) </td>
            @*<td>
                    @Html.ActionLink("Edit", "Edit", new { id = branch.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = branch.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = branch.Id })
                </td>*@
        </tr>
    }

</table>

SaveTime.Web.Admin/Views/Company/Edit.cshtml
@model SaveTime.DataModel.Organization.Company

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SaveTime.Web.Admin/Views/Company/Index.cshtml
@model SaveTime.Web.Admin.Models.Company.CompanyViewModel

@{
    ViewBag.Title = "Index";
    int selfId;
}
<div class="container-fluid">
    <div class=" row">
        <div class="col-lg-12">
            <h2>Company</h2>

            <table class="table" id="companies-table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.CreateCompany.Id)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreateCompany.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CreateCompany.City)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model.Companies)
                {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.City)
                </td>
                <td>
                    @*@Html.ActionLink("Edit", "Edit", new { id = item.Id }) |*@
                    @*@Html.ActionLink("Details", "Details", new { id = item.Id, onclick = $"GetDetails({item.Id})" }) |*@
                    <a data-id="@item.Id" class="company-details" href="#">Details</a> |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
                }

            </table>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            @Html.Partial("_CreateCompany");
        </div>
        <div class="col-lg-6">
            @Html.Partial("_EditCompany")
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12" id="companyDetails">

        </div>
    </div>
</div>

@section scripts{
    <script>
        function GetCompanies() {
              $.get("/Company/GetCompanies", null, function (listofcompanies) {
                    var tbody = "<tbody>";
                    for (var i = 0; i < listofcompanies.length; i++) {
                        
                    console.log(listofcompanies[i]);
                        var tr = "<tr>";
                        var td = "<td>";
                        td += (listofcompanies[i].Name);
                        td += "</td>";
                        tr += td;

                        td = "<td>";
                        td += (listofcompanies[i].City);
                        td += "</td>";
                        tr += td;

                        tr += "</tr>";
                        tbody += tr;

                        tbody += "</tbody>";
                    }

                    console.log(tbody);

                    $("#companies-table").html(tbody);
                });
        }


        $(".company-details").on("click", function () {
            $("#companyDetails").load("@Url.Action("Details","Company")/" + $(this).attr("data-id"))
        })

        $("#btn-edit").on("click", function (e) {
            e.preventDefault();
            var dataEdit = $("#form-edit").serialize();
            console.log("data Edit:", dataEdit);
            $.post("/Company/Edit", dataEdit, function (value) {

            }).then(GetCompanies());
        })

        $("#btn-create").on("click", function (e) {
                e.preventDefault();
               var data = $("#form-create").serialize();
               console.log(data);

           
            $.post("/Company/Create", data, function (value) {
                //alert(value);
            }).then(GetCompanies());

        })

    </script>
}

SaveTime.Web.Admin/Views/Company/_CreateCompany.cshtml
@model SaveTime.Web.Admin.Models.Company.CompanyViewModel


<h2>Create</h2>


<form action="/Company/Create/" method= "post" id="form-create">
    @Html.AntiForgeryToken()

    <div class="form-horizontal" >
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CreateCompany.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateCompany.Name, new { htmlAttributes = new { @class = "form-control", Name="Name" } })
                @Html.ValidationMessageFor(model => model.CreateCompany.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateCompany.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateCompany.City, new { htmlAttributes = new { @class = "form-control",  Name="City" } })
                @Html.ValidationMessageFor(model => model.CreateCompany.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" id="btn-create" />
            </div>
        </div>
    </div>
</form>


@section Scripts {
    @*<script>
        $("#btn-create").on("click", function (e) {
            var data = $("#form-create").serialize();

            e.preventDefault();
            $.post("/Company/Create/", data, function (value) {
                alert(value);
            });

        })
    </script>*@
    @Scripts.Render("~/bundles/jqueryval")
}

SaveTime.Web.Admin/Views/Company/_EditCompany.cshtml
@model SaveTime.Web.Admin.Models.Company.CompanyViewModel


<h2>Edit</h2>


<form action="/Company/Edit/" method="post" id="form-edit">
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Company</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.Id)*@

        <div class="form-group">
            @Html.LabelFor(model => model.CreateCompany.Id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateCompany.Id, new { htmlAttributes = new { @class = "form-control", Name="Id" } })
                @Html.ValidationMessageFor(model => model.CreateCompany.Id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateCompany.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateCompany.Name, new { htmlAttributes = new { @class = "form-control", Name="Name" } })
                @Html.ValidationMessageFor(model => model.CreateCompany.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CreateCompany.City, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CreateCompany.City, new { htmlAttributes = new { @class = "form-control", Name="City" } })
                @Html.ValidationMessageFor(model => model.CreateCompany.City, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" id="btn-edit"/>
            </div>
        </div>
    </div>
</form>